version: "3"

services:
  datapassport-backend:
    container_name: "datapassport-backend"
    restart: unless-stopped
    env_file:
      - .env
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    ports:
      - ${PORT:-80}:${PORT:-80}
    command: dev
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 20      
    env_file:
      - .env
    ports:
      - 5432:5432

volumes:
  postgres_data:
