version: "3.8"
services:
  c2d-crm:
    container_name: "c2d-crm"
    image: "c2d-crm:latest"
    env_file:
      - .env
    build:
      context: ./
      dockerfile: Dockerfile
      labels:
        - c2d-crm
    volumes:
        - .:/code
    ports:
      - "0.0.0.0:21188:5000"
