version: "3.8"
services:
  c2d-crm:
    container_name: "c2d-crm"
    image: "c2d-crm:latest"
    restart: unless-stopped
    env_file:
      - .env
    build:
      context: ./
      dockerfile: Dockerfile
      labels:
        - c2d-crm
    volumes:
        - .:/code
    ports:
      - "0.0.0.0:21188:21188"
    command: uvicorn --log-level info --reload --host 0.0.0.0 --port 21188 main:app