name: CI

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main
      - dev

env:
  REGISTRY: 126761267783.dkr.ecr.us-east-1.amazonaws.com/datapassport

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Container - Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: Container - Setup Buildx
        uses: docker/setup-buildx-action@v1

      - name: Container - Meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ${{ env.REGISTRY }}
          tags: |
            type=sha,format=long

      - name: Container - Build & Push
        uses: docker/build-push-action@v2
        with:
          push: false
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64
          cache-from: type=registry,ref=${{ env.REGISTRY }}:latest

      - name: Run E2E tests
        run: make test
